services:
  django:
    build: 
      context: ../
      dockerfile: ./development/dockerfile
    container_name: 'django-dev'
    volumes:
      - ../django:/app
    ports:
      - 8000:8000
    env_file:
      - .env