services:

  daphne:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: 'daphne'
    volumes:
      - ./django:/app
      - static_db:/app/static
    depends_on:
      - database
    networks:
      - app_network
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: 'database'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: 'nginx'
    ports:
      - "1025:1025"
    depends_on:
      - daphne
    volumes:
      - static_db:/app/static
    networks:
      - app_network
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
  static_db:
    driver: local

networks:
  app_network:
    driver: bridge