services:

  daphne:
    build:
      context: ./django
      dockerfile: Dockerfile
    container_name: 'daphne'
    volumes:
      - ./django:/app
      - static_db:/app/static
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_network
    env_file:
      - .env

  database:
    image: postgres:latest
    container_name: 'database'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: 'nginx'
    ports:
      - "1025:1025"
    depends_on:
      - daphne
    volumes:
      - static_db:/app/static
    networks:
      - app_network
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local
  static_db:
    driver: local

networks:
  app_network:
    driver: bridge