from django.urls import path
from . import views

urlpatterns = [
    path('user/<username>/', views.user_view, name="user"),
    path('user/<username>/friends', views.user_view_friends, name="user_friends"),
    path('user/<username>/info', views.user_view_info, name="user_info"),
    path('block/', views.block_user, name="block_user"),
    path('', views.index_view, name="index"),
    path('invitation/create/', views.create_invitation, name="invitation_create"),
    path('invitation/dismiss/', views.dismiss_invitation, name="invitation_dismiss"),
    path('invitation/accept/', views.accept_invitation, name="invitation_accept"),
    path('invitation/cancel/', views.cancel_invitation, name="invitation_cancel"),
    path('invitation/uninvited/', views.uninvited_users, name="uninvited_users"),
    path('messages/', views.chat_messages_form, name="chat_messages"),
    path('messages/send/', views.send_message, name="send_message"),
    path('messages/list/', views.list_messages, name="list_messages"),
    path('tournament/<int:tournament_id>/', views.tournament_view, name="tournament"),
    path('tournament/<int:tournament_id>/remove_competitor/', views.tournament_remove_competitor, name="tournament_remove_competitor"),
    path('tournament/<int:tournament_id>/disqualify_competitor/', views.tournament_disqualify_competitor, name="tournament_disqualify_competitor"),
    path('tournament/<int:tournament_id>/add_competitor/', views.tournament_register_competitor, name="tournament_add_competitor"),
    path('tournament/<int:tournament_id>/start/', views.tournament_start, name="tournament_start"),
    path('tournament/<int:tournament_id>/competitor_list/', views.tournament_competitors, name="tournament_competitor_list"),
    path('tournament/<int:tournament_id>/remove/', views.tournament_remove, name="tournament_remove"),
    path('tournament/list/', views.tournament_list, name="tournament_list"),
    path('tournament/list/update', views.tournament_list_update, name="tournament_list_update"),
    path('tournament/create/', views.tournament_create, name="tournament_create"),
    path('three/', views.three_demo, name="three"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('game/<int:game_id>/', views.game_view, name="game"),
    path('logout/', views.logout, name="logout"),
    path('login/options/', views.login_options, name="login_options"),
    path('login/', views.login, name="login"),
    path('register/', views.register_view, name="register"),
    path('match/create/', views.create_match, name="create_match"),
]
